AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EmailParameter:
    Type: String
  MailgunDomainParameter:
    Type: String
Resources:
  MailgunEventTopic:
    Properties:
      Subscription:
      - Endpoint:
          Ref: EmailParameter
        Protocol: email
    Type: AWS::SNS::Topic
  PermanentFailFunction:
    Properties:
      CodeUri: s3://sam-quantumsense-ai/ec4b67f25c54861db620eda73ef3843d
      Environment:
        Variables:
          MAILGUN_DOMAIN:
            Ref: MailgunDomainParameter
          SNS_TOPIC_ARN:
            Ref: MailgunEventTopic
      Events:
        MailgunWebhookApi:
          Properties:
            Method: POST
            Path: /
          Type: Api
      Handler: permanent-fail.handler
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - MailgunEventTopic
            - TopicName
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
