AWSTemplateFormatVersion: '2010-09-09'
Globals:
  Function:
    CodeUri: .
    Environment:
      Variables:
        MAILGUN_DOMAIN:
          Ref: MailgunDomainParameter
        SNS_TOPIC_ARN:
          Ref: MailgunEventTopic
    Runtime: nodejs8.10
    Timeout: 10
Parameters:
  MailgunDomainParameter:
    Type: String
  SnsEmailParameter:
    Type: String
Resources:
  MailgunEventTopic:
    Properties:
      Subscription:
      - Endpoint:
          Ref: SnsEmailParameter
        Protocol: email
    Type: AWS::SNS::Topic
  PermanentFailFunction:
    Properties:
      CodeUri: s3://sam-quantumsense-ai/4ec317236f0eb17a14295d0020064fdb
      Events:
        MailgunWebhookApi:
          Properties:
            Method: POST
            Path: /failed-permanent
          Type: Api
      Handler: failed-permanent.handler
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - MailgunEventTopic
            - TopicName
    Type: AWS::Serverless::Function
  TemporaryFailFunction:
    Properties:
      CodeUri: s3://sam-quantumsense-ai/4ec317236f0eb17a14295d0020064fdb
      Events:
        MailgunWebhookApi:
          Properties:
            Method: POST
            Path: /failed-temporary
          Type: Api
      Handler: failed-temporary.handler
      Policies:
      - SNSPublishMessagePolicy:
          TopicName:
            Fn::GetAtt:
            - MailgunEventTopic
            - TopicName
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
