AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  SnsEmailParameter:
    Type: String
  MailgunDomainParameter:
    Type: String

Globals:
  Function:
    CodeUri: .
    Runtime: nodejs8.10
    Timeout: 10
    Environment:
      Variables:
        SNS_TOPIC_ARN: !Ref MailgunEventTopic
        MAILGUN_DOMAIN: !Ref MailgunDomainParameter    

Resources:
  PermanentFailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: failed-permanent.handler
      Events:
        MailgunWebhookApi:
          Type: Api
          Properties:
           Path: /failed-permanent
           Method: POST
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MailgunEventTopic.TopicName

  TemporaryFailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: failed-temporary.handler
      Events:
        MailgunWebhookApi:
          Type: Api
          Properties:
           Path: /failed-temporary
           Method: POST
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MailgunEventTopic.TopicName

  MailgunEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref SnsEmailParameter
          Protocol: email
