AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  EmailParameter:
    Type: String
  MailgunDomainParameter:
    Type: String

Resources:
  PermanentFailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: permanent-fail.handler
      Runtime: nodejs8.10
      Timeout: 10
      Events:
        MailgunWebhookApi:
          Type: Api
          Properties:
           Path: /
           Method: POST
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MailgunEventTopic.TopicName
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MailgunEventTopic
          MAILGUN_DOMAIN: !Ref MailgunDomainParameter

  MailgunEventTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Endpoint: !Ref EmailParameter
          Protocol: email
